### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by peterccarl** [AnthonyChristidis/RPEIF#1]
Hi Anthony,

When I try to install from github:
> devtools::install_github("AnthonyChristidis/IFs")

I receive the following error:
...
configure: creating ./config.status
config.status: error: cannot find input file: `src/Makevars.in'
ERROR: configuration failed for package ‘IFs’

Did you miss a file when committing?

Thanks! 

pcc

**Comment by AnthonyChristidis** [comment]
Fixed.
